In [22]:
# %pip install numpy

In [23]:
# pip install --upgrade pip

In [24]:
import numpy as np

In [25]:
list = [ 1,2,3,4,5]
type(list)

list

In [26]:
array1 = np.array([1,2,3,4,5])
type(array1)

numpy.ndarray

In [27]:
print(arr3d.ndim)

NameError: name 'arr3d' is not defined

In [ ]:
arr3d.shape

(1, 3, 2)

In [ ]:
arr2d.dtype

dtype('int64')

In [ ]:
arr2d = np.array([[1,2],[3,4]])
arr2d

array([[1, 2],
       [3, 4]])

In [ ]:
arr3d = np.array([[[1,2],[3,4],[4,5]]])
arr3d

array([[[1, 2],
        [3, 4],
        [4, 5]]])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/Users/rashmithav/Desktop/Desktop/datasets_dataminds/user_behavior_missing data-2.csv')

In [ ]:
df.shape

(700, 11)

In [ ]:
df.head(20)

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN,3
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female,3
5,6,Google Pixel 5,NaN,99.0,2.0,940.0,35.0,564,31,NaN,2
6,7,Samsung Galaxy S21,Android,350.0,7.3,1802.0,66.0,1054,21,Female,4
7,8,OnePlus 9,Android,543.0,11.4,2956.0,82.0,1702,31,Male,5
8,9,Samsung Galaxy S21,Android,340.0,7.7,2138.0,75.0,1053,42,Female,4
9,10,iPhone 12,iOS,424.0,6.6,1957.0,75.0,1301,42,NaN,4
10,11,Google Pixel 5,Android,53.0,1.4,435.0,17.0,162,34,Female,1
11,12,OnePlus 9,Android,215.0,5.5,1690.0,47.0,641,24,Male,3
12,13,OnePlus 9,Android,462.0,NaN,2303.0,65.0,1099,57,Female,4
13,14,Xiaomi Mi 11,Android,215.0,4.9,1662.0,43.0,857,43,Male,3
14,15,iPhone 12,iOS,189.0,5.4,1754.0,53.0,779,49,Female,3
15,16,Google Pixel 5,Android,503.0,10.4,2571.0,84.0,2025,39,Female,5
16,17,OnePlus 9,Android,132.0,3.6,628.0,32.0,344,47,Female,2
17,18,iPhone 12,iOS,299.0,5.8,1431.0,41.0,985,44,Female,3
18,19,Google Pixel 5,Android,81.0,1.4,558.0,16.0,297,26,Female,1
19,20,iPhone 12,iOS,577.0,NaN,2774.0,89.0,2192,29,Female,5

In [ ]:
df.tail(20)

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
680,681,Google Pixel 5,Android,307.0,6.1,2105.0,76.0,1111,25,Female,4
681,682,Xiaomi Mi 11,Android,380.0,7.6,2354.0,77.0,1191,30,Male,4
682,683,Xiaomi Mi 11,Android,190.0,5.5,1718.0,58.0,815,42,Male,3
683,684,Samsung Galaxy S21,Android,75.0,1.6,325.0,12.0,225,45,Male,1
684,685,Google Pixel 5,Android,218.0,4.0,1221.0,47.0,822,25,Male,3
685,686,Xiaomi Mi 11,Android,412.0,6.6,1859.0,67.0,1393,18,Male,4
686,687,Google Pixel 5,Android,335.0,7.7,2037.0,68.0,1007,18,Male,4
687,688,OnePlus 9,Android,387.0,6.3,2098.0,61.0,1178,54,Male,4
688,689,Google Pixel 5,Android,261.0,4.9,1589.0,56.0,824,52,Female,3
689,690,Samsung Galaxy S21,Android,541.0,9.5,2424.0,98.0,1550,32,Male,5
690,691,Google Pixel 5,Android,195.0,5.7,1447.0,48.0,679,30,Male,3
691,692,iPhone 12,iOS,178.0,4.0,856.0,37.0,569,51,Female,2
692,693,Xiaomi Mi 11,Android,378.0,6.7,1898.0,78.0,1455,48,Female,4
693,694,Xiaomi Mi 11,Android,505.0,8.6,2792.0,82.0,1709,31,Male,5
694,695,Samsung Galaxy S21,Android,564.0,9.7,2422.0,83.0,1985,34,Female,5
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male,4
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male,1
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female,3

In [ ]:
df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User ID                     700 non-null    int64
 1   Device Model                700 non-null    object
 2   Operating System            694 non-null    object
 3   App Usage Time (min/day)    695 non-null    float64
 4   Screen On Time (hours/day)  691 non-null    float64
 5   Battery Drain (mAh/day)     699 non-null    float64
 6   Number of Apps Installed    699 non-null    float64
 7   Data Usage (MB/day)         700 non-null    int64
 8   Age                         700 non-null    int64
 9   Gender                      691 non-null    object
 10  User Behavior Class         700 non-null    int64
dtypes: float64(4), int64(4), object(3)
memory usage: 60.3+ KB

In [ ]:
df.describe()

,User ID,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,User Behavior Class
count,700.00000,695.000000,691.000000,699.000000,699.000000,700.000000,700.000000,700.000000
mean,350.50000,270.943885,5.262952,1524.459227,50.623748,929.742857,38.482857,2.990000
std,202.21688,177.044617,3.068350,819.513827,26.919333,640.451729,12.012916,1.401476
min,1.00000,30.000000,1.000000,302.000000,10.000000,102.000000,18.000000,1.000000
25%,175.75000,112.500000,2.500000,721.500000,26.000000,373.000000,28.000000,2.000000
50%,350.50000,227.000000,4.900000,1500.000000,49.000000,823.500000,38.000000,3.000000
75%,525.25000,432.500000,7.400000,2230.000000,74.000000,1341.000000,49.000000,4.000000
max,700.00000,598.000000,12.000000,2993.000000,99.000000,2497.000000,59.000000,5.000000

In [ ]:
df.sample(5)

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
609,610,iPhone 12,iOS,551.0,8.5,2927.0,92.0,1901,51,Male,5
628,629,Xiaomi Mi 11,Android,47.0,1.2,437.0,18.0,234,55,Male,1
306,307,OnePlus 9,Android,243.0,5.0,1232.0,47.0,877,43,Male,3
209,210,Google Pixel 5,Android,278.0,4.6,1385.0,47.0,823,40,Female,3
320,321,iPhone 12,iOS,227.0,4.4,1275.0,56.0,984,22,Female,3

In [ ]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr_float= arr.astype(np.float32)
arr_float

array([10., 20., 30., 40.], dtype=float32)

In [ ]:
arr_float = arr_float.astype(np.int16)
arr_float

array([10, 20, 30, 40], dtype=int16)

In [ ]:
arr = np.array([10,20,30,40,],dtype = np.int32)
arr.dtype

dtype('int32')

In [ ]:
df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [ ]:
df['App Usage Time (min/day)'].dtype

dtype('float64')

In [ ]:
usage_array = df['App Usage Time (min/day)']
usage_array

0      393.0
1      268.0
2      154.0
3      239.0
4      187.0
       ...
695     92.0
696    316.0
697     99.0
698     62.0
699    212.0
Name: App Usage Time (min/day), Length: 700, dtype: float64

In [ ]:
pip insatll pandas

In [ ]:
import pandas as pd

In [ ]:
usage_array = pd.Series(df['App Usage Time (min/day)'])
usage_array

0      393.0
1      268.0
2      154.0
3      239.0
4      187.0
       ...
695     92.0
696    316.0
697     99.0
698     62.0
699    212.0
Name: App Usage Time (min/day), Length: 700, dtype: float64

In [ ]:
type(usage_array)

pandas.core.series.Series

In [ ]:
usage_array = np.array(df['App Usage Time (min/day)'])
usage_array

array([393., 268., 154., 239., 187.,  99., 350., 543., 340., 424.,  53.,
       215., 462., 215., 189., 503., 132., 299.,  81., 577.,  93., 576.,
       423., 292., 216.,  91., 444., 512., 452., 412., 260., 197., 278.,
        46., 593.,  32., 122., 522., 473., 398., 240., 576., 120., 152.,
       138., 502., 558., 138., 580.,  nan,  nan,  nan,  nan,  97., 516.,
        68.,  64., 539., 428., 325., 522., 309.,  79., 545., 459., 225.,
       257., 134., 516.,  82., 452., 521., 457.,  31.,  47., 229.,  34.,
       173.,  78., 230., 565., 172., 330.,  39., 223., 404., 151.,  34.,
       137., 301., 116., 291.,  84., 134., 411., 326., 550., 516.,  59.,
       225.,  41., 183., 174., 274., 166.,  66., 152.,  54., 187., 216.,
        95., 488., 295., 136., 471., 121.,  75., 220.,  82.,  97., 388.,
       529., 584., 529., 227., 535., 332., 252., 125.,  97., 540., 320.,
       176.,  79.,  83., 555.,  66., 237., 497., 516., 219., 448., 156.,
        68., 524., 188., 443.,  52., 228., 149., 523.,  42., 120., 329.,
        68., 158.,  86., 339., 304., 131.,  64.,  53., 442.,  32., 278.,
       540., 595.,  35., 225., 587.,  92.,  46., 153., 368.,  51., 279.,
       255., 193., 207., 539., 151., 474., 544.,  nan, 597., 498., 402.,
        75., 130.,  42., 134.,  79., 432., 262., 473., 202., 215., 151.,
        80., 126., 495., 127.,  88.,  69., 100., 301.,  78., 163., 539.,
       278., 451., 481., 133.,  41., 152., 553., 402., 555., 499., 101.,
       433., 133., 351., 532.,  92., 511., 384., 193., 132., 360., 159.,
       495., 537., 129., 132.,  37., 524., 425.,  64., 573.,  45., 564.,
       162., 451.,  30., 202.,  71., 314., 168.,  75.,  42., 441., 523.,
       100.,  52., 397., 424., 272., 201., 570.,  64., 334., 518.,  70.,
       334., 563., 181., 584., 208., 381., 426., 284., 105., 179., 122.,
       501., 269., 230.,  85., 411.,  73.,  39., 386.,  49., 411., 534.,
       314., 211., 121.,  84., 448.,  55.,  59., 226., 580.,  65., 458.,
       170., 264., 122., 420., 267., 469., 541., 155., 106., 243., 410.,
       285., 397., 230., 341., 132., 130., 281.,  74., 299., 116., 408.,
       508., 227., 274., 347.,  76., 445., 203., 199.,  48.,  88., 541.,
       233., 176., 191., 461.,  37., 531., 473.,  30., 306.,  64.,  75.,
       597., 529., 290., 256., 308., 156.,  62., 156., 303., 463.,  60.,
       225., 379.,  53.,  30., 291., 488.,  74., 230., 517., 557.,  78.,
       321., 579., 382., 516., 598., 102., 165., 558., 561., 511., 560.,
        69.,  44.,  65., 458., 525., 106., 188., 493.,  84., 104., 102.,
       349.,  98.,  72., 563., 119., 311., 337., 168., 331., 589., 472.,
        78., 517.,  41.,  49., 522.,  97., 411., 566., 559., 478., 147.,
       395., 357., 405., 501., 575., 257., 270., 116.,  98., 264., 572.,
       202.,  83.,  32., 168., 416.,  46., 201., 130.,  98., 105.,  94.,
       540., 266., 140., 534.,  46., 581., 105., 221.,  41., 105., 123.,
       260., 223.,  66., 231., 555., 378., 546., 234., 152.,  34., 179.,
       591., 120.,  88., 143.,  74.,  74., 234.,  56., 174., 523., 123.,
       216., 290.,  68., 265., 414., 238., 429.,  39., 248., 541., 139.,
       289., 210., 412., 318., 258., 258., 189., 155., 528., 549.,  78.,
       444.,  80., 131., 228., 416., 586., 416., 152.,  87., 329., 107.,
       493., 182., 102., 274., 143.,  66., 420., 582., 200., 493., 348.,
       238.,  33., 267., 492., 241., 567.,  36., 110., 466., 126., 120.,
        64., 574., 119., 350.,  69., 438., 506., 272., 224.,  99.,  44.,
       175., 228., 589., 339., 431., 190., 389., 139., 289., 593., 576.,
       592., 567., 170., 242., 275., 544.,  50., 236., 139., 383., 172.,
       455., 157., 173., 405., 387., 201., 142., 198., 361., 553., 408.,
       121.,  71.,  46., 290.,  60., 116.,  86., 291., 404., 441., 444.,
       211., 537., 519.,  94., 554., 381., 257.,  47., 527., 148., 191.,
        71.,  73., 149., 197., 328., 424., 111., 159., 580., 379., 217.,
       447., 512., 511., 140., 114., 192., 325.,  83., 122., 138., 182.,
       425., 580., 203., 258., 551., 507.,  57., 553.,  49., 106., 119.,
       288., 225., 342., 292., 218.,  64., 453.,  42.,  36.,  55., 210.,
       227.,  47., 461.,  94., 216., 496., 138., 318.,  96., 510.,  83.,
       417., 538.,  63.,  50., 502., 105., 186., 174.,  89.,  66., 389.,
       186., 149.,  69., 206.,  49., 594., 104., 262., 278., 463., 505.,
        50., 138., 130., 469., 555., 198., 529., 205., 170., 160.,  81.,
       468., 500.,  37., 522.,  81., 141., 115., 298.,  33., 307., 380.,
       190.,  75., 218., 412., 335., 387., 261., 541., 195., 178., 378.,
       505., 564.,  92., 316.,  99.,  62., 212.])

In [ ]:
usage_array = df['App Usage Time (min/day)'].to_numpy()
usage_array

array([393., 268., 154., 239., 187.,  99., 350., 543., 340., 424.,  53.,
       215., 462., 215., 189., 503., 132., 299.,  81., 577.,  93., 576.,
       423., 292., 216.,  91., 444., 512., 452., 412., 260., 197., 278.,
        46., 593.,  32., 122., 522., 473., 398., 240., 576., 120., 152.,
       138., 502., 558., 138., 580.,  nan,  nan,  nan,  nan,  97., 516.,
        68.,  64., 539., 428., 325., 522., 309.,  79., 545., 459., 225.,
       257., 134., 516.,  82., 452., 521., 457.,  31.,  47., 229.,  34.,
       173.,  78., 230., 565., 172., 330.,  39., 223., 404., 151.,  34.,
       137., 301., 116., 291.,  84., 134., 411., 326., 550., 516.,  59.,
       225.,  41., 183., 174., 274., 166.,  66., 152.,  54., 187., 216.,
        95., 488., 295., 136., 471., 121.,  75., 220.,  82.,  97., 388.,
       529., 584., 529., 227., 535., 332., 252., 125.,  97., 540., 320.,
       176.,  79.,  83., 555.,  66., 237., 497., 516., 219., 448., 156.,
        68., 524., 188., 443.,  52., 228., 149., 523.,  42., 120., 329.,
        68., 158.,  86., 339., 304., 131.,  64.,  53., 442.,  32., 278.,
       540., 595.,  35., 225., 587.,  92.,  46., 153., 368.,  51., 279.,
       255., 193., 207., 539., 151., 474., 544.,  nan, 597., 498., 402.,
        75., 130.,  42., 134.,  79., 432., 262., 473., 202., 215., 151.,
        80., 126., 495., 127.,  88.,  69., 100., 301.,  78., 163., 539.,
       278., 451., 481., 133.,  41., 152., 553., 402., 555., 499., 101.,
       433., 133., 351., 532.,  92., 511., 384., 193., 132., 360., 159.,
       495., 537., 129., 132.,  37., 524., 425.,  64., 573.,  45., 564.,
       162., 451.,  30., 202.,  71., 314., 168.,  75.,  42., 441., 523.,
       100.,  52., 397., 424., 272., 201., 570.,  64., 334., 518.,  70.,
       334., 563., 181., 584., 208., 381., 426., 284., 105., 179., 122.,
       501., 269., 230.,  85., 411.,  73.,  39., 386.,  49., 411., 534.,
       314., 211., 121.,  84., 448.,  55.,  59., 226., 580.,  65., 458.,
       170., 264., 122., 420., 267., 469., 541., 155., 106., 243., 410.,
       285., 397., 230., 341., 132., 130., 281.,  74., 299., 116., 408.,
       508., 227., 274., 347.,  76., 445., 203., 199.,  48.,  88., 541.,
       233., 176., 191., 461.,  37., 531., 473.,  30., 306.,  64.,  75.,
       597., 529., 290., 256., 308., 156.,  62., 156., 303., 463.,  60.,
       225., 379.,  53.,  30., 291., 488.,  74., 230., 517., 557.,  78.,
       321., 579., 382., 516., 598., 102., 165., 558., 561., 511., 560.,
        69.,  44.,  65., 458., 525., 106., 188., 493.,  84., 104., 102.,
       349.,  98.,  72., 563., 119., 311., 337., 168., 331., 589., 472.,
        78., 517.,  41.,  49., 522.,  97., 411., 566., 559., 478., 147.,
       395., 357., 405., 501., 575., 257., 270., 116.,  98., 264., 572.,
       202.,  83.,  32., 168., 416.,  46., 201., 130.,  98., 105.,  94.,
       540., 266., 140., 534.,  46., 581., 105., 221.,  41., 105., 123.,
       260., 223.,  66., 231., 555., 378., 546., 234., 152.,  34., 179.,
       591., 120.,  88., 143.,  74.,  74., 234.,  56., 174., 523., 123.,
       216., 290.,  68., 265., 414., 238., 429.,  39., 248., 541., 139.,
       289., 210., 412., 318., 258., 258., 189., 155., 528., 549.,  78.,
       444.,  80., 131., 228., 416., 586., 416., 152.,  87., 329., 107.,
       493., 182., 102., 274., 143.,  66., 420., 582., 200., 493., 348.,
       238.,  33., 267., 492., 241., 567.,  36., 110., 466., 126., 120.,
        64., 574., 119., 350.,  69., 438., 506., 272., 224.,  99.,  44.,
       175., 228., 589., 339., 431., 190., 389., 139., 289., 593., 576.,
       592., 567., 170., 242., 275., 544.,  50., 236., 139., 383., 172.,
       455., 157., 173., 405., 387., 201., 142., 198., 361., 553., 408.,
       121.,  71.,  46., 290.,  60., 116.,  86., 291., 404., 441., 444.,
       211., 537., 519.,  94., 554., 381., 257.,  47., 527., 148., 191.,
        71.,  73., 149., 197., 328., 424., 111., 159., 580., 379., 217.,
       447., 512., 511., 140., 114., 192., 325.,  83., 122., 138., 182.,
       425., 580., 203., 258., 551., 507.,  57., 553.,  49., 106., 119.,
       288., 225., 342., 292., 218.,  64., 453.,  42.,  36.,  55., 210.,
       227.,  47., 461.,  94., 216., 496., 138., 318.,  96., 510.,  83.,
       417., 538.,  63.,  50., 502., 105., 186., 174.,  89.,  66., 389.,
       186., 149.,  69., 206.,  49., 594., 104., 262., 278., 463., 505.,
        50., 138., 130., 469., 555., 198., 529., 205., 170., 160.,  81.,
       468., 500.,  37., 522.,  81., 141., 115., 298.,  33., 307., 380.,
       190.,  75., 218., 412., 335., 387., 261., 541., 195., 178., 378.,
       505., 564.,  92., 316.,  99.,  62., 212.])

In [ ]:
array_data = df.to_numpy()
array_data

array([[1, 'Google Pixel 5', 'Android', ..., 40, 'Male', 4],
       [2, 'OnePlus 9', 'Android', ..., 47, 'Female', 3],
       [3, 'Xiaomi Mi 11', 'Android', ..., 42, nan, 2],
       ...,
       [698, 'Google Pixel 5', 'Android', ..., 50, 'Female', 2],
       [699, 'Samsung Galaxy S21', 'Android', ..., 44, 'Male', 1],
       [700, 'OnePlus 9', 'Android', ..., 23, 'Female', 3]], dtype=object)

In [ ]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_array = numeric_df.to_numpy()
numeric_array

array([[1.000e+00, 3.930e+02, 6.400e+00, ..., 1.122e+03, 4.000e+01,
        4.000e+00],
       [2.000e+00, 2.680e+02, 4.700e+00, ..., 9.440e+02, 4.700e+01,
        3.000e+00],
       [3.000e+00, 1.540e+02, 4.000e+00, ..., 3.220e+02, 4.200e+01,
        2.000e+00],
       ...,
       [6.980e+02, 9.900e+01, 3.100e+00, ..., 4.570e+02, 5.000e+01,
        2.000e+00],
       [6.990e+02, 6.200e+01, 1.700e+00, ..., 2.240e+02, 4.400e+01,
        1.000e+00],
       [7.000e+02, 2.120e+02, 5.400e+00, ..., 8.280e+02, 2.300e+01,
        3.000e+00]])

In [ ]:
zeros_array = np.zeros(usage_array.shape)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
ones_array = np.ones(usage_array.shape)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
range_array =np.arange(len(usage_array))
range_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699])

In [ ]:
linspace_array = np.linspace(0,10, len(usage_array))
linspace_array

array([ 0.        ,  0.01430615,  0.0286123 ,  0.04291845,  0.05722461,
        0.07153076,  0.08583691,  0.10014306,  0.11444921,  0.12875536,
        0.14306152,  0.15736767,  0.17167382,  0.18597997,  0.20028612,
        0.21459227,  0.22889843,  0.24320458,  0.25751073,  0.27181688,
        0.28612303,  0.30042918,  0.31473534,  0.32904149,  0.34334764,
        0.35765379,  0.37195994,  0.38626609,  0.40057225,  0.4148784 ,
        0.42918455,  0.4434907 ,  0.45779685,  0.472103  ,  0.48640916,
        0.50071531,  0.51502146,  0.52932761,  0.54363376,  0.55793991,
        0.57224607,  0.58655222,  0.60085837,  0.61516452,  0.62947067,
        0.64377682,  0.65808298,  0.67238913,  0.68669528,  0.70100143,
        0.71530758,  0.72961373,  0.74391989,  0.75822604,  0.77253219,
        0.78683834,  0.80114449,  0.81545064,  0.8297568 ,  0.84406295,
        0.8583691 ,  0.87267525,  0.8869814 ,  0.90128755,  0.91559371,
        0.92989986,  0.94420601,  0.95851216,  0.97281831,  0.98712446,
        1.00143062,  1.01573677,  1.03004292,  1.04434907,  1.05865522,
        1.07296137,  1.08726753,  1.10157368,  1.11587983,  1.13018598,
        1.14449213,  1.15879828,  1.17310443,  1.18741059,  1.20171674,
        1.21602289,  1.23032904,  1.24463519,  1.25894134,  1.2732475 ,
        1.28755365,  1.3018598 ,  1.31616595,  1.3304721 ,  1.34477825,
        1.35908441,  1.37339056,  1.38769671,  1.40200286,  1.41630901,
        1.43061516,  1.44492132,  1.45922747,  1.47353362,  1.48783977,
        1.50214592,  1.51645207,  1.53075823,  1.54506438,  1.55937053,
        1.57367668,  1.58798283,  1.60228898,  1.61659514,  1.63090129,
        1.64520744,  1.65951359,  1.67381974,  1.68812589,  1.70243205,
        1.7167382 ,  1.73104435,  1.7453505 ,  1.75965665,  1.7739628 ,
        1.78826896,  1.80257511,  1.81688126,  1.83118741,  1.84549356,
        1.85979971,  1.87410587,  1.88841202,  1.90271817,  1.91702432,
        1.93133047,  1.94563662,  1.95994278,  1.97424893,  1.98855508,
        2.00286123,  2.01716738,  2.03147353,  2.04577969,  2.06008584,
        2.07439199,  2.08869814,  2.10300429,  2.11731044,  2.1316166 ,
        2.14592275,  2.1602289 ,  2.17453505,  2.1888412 ,  2.20314735,
        2.21745351,  2.23175966,  2.24606581,  2.26037196,  2.27467811,
        2.28898426,  2.30329041,  2.31759657,  2.33190272,  2.34620887,
        2.36051502,  2.37482117,  2.38912732,  2.40343348,  2.41773963,
        2.43204578,  2.44635193,  2.46065808,  2.47496423,  2.48927039,
        2.50357654,  2.51788269,  2.53218884,  2.54649499,  2.56080114,
        2.5751073 ,  2.58941345,  2.6037196 ,  2.61802575,  2.6323319 ,
        2.64663805,  2.66094421,  2.67525036,  2.68955651,  2.70386266,
        2.71816881,  2.73247496,  2.74678112,  2.76108727,  2.77539342,
        2.78969957,  2.80400572,  2.81831187,  2.83261803,  2.84692418,
        2.86123033,  2.87553648,  2.88984263,  2.90414878,  2.91845494,
        2.93276109,  2.94706724,  2.96137339,  2.97567954,  2.98998569,
        3.00429185,  3.018598  ,  3.03290415,  3.0472103 ,  3.06151645,
        3.0758226 ,  3.09012876,  3.10443491,  3.11874106,  3.13304721,
        3.14735336,  3.16165951,  3.17596567,  3.19027182,  3.20457797,
        3.21888412,  3.23319027,  3.24749642,  3.26180258,  3.27610873,
        3.29041488,  3.30472103,  3.31902718,  3.33333333,  3.34763948,
        3.36194564,  3.37625179,  3.39055794,  3.40486409,  3.41917024,
        3.43347639,  3.44778255,  3.4620887 ,  3.47639485,  3.490701  ,
        3.50500715,  3.5193133 ,  3.53361946,  3.54792561,  3.56223176,
        3.57653791,  3.59084406,  3.60515021,  3.61945637,  3.63376252,
        3.64806867,  3.66237482,  3.67668097,  3.69098712,  3.70529328,
        3.71959943,  3.73390558,  3.74821173,  3.76251788,  3.77682403,
        3.79113019,  3.80543634,  3.81974249,  3.83404864,  3.84835479,
        3.86266094,  3.8769671 ,  3.89127325,  3.9055794 ,  3.91988555,
        3.9341917 ,  3.94849785,  3.96280401,  3.97711016,  3.99141631,
        4.00572246,  4.02002861,  4.03433476,  4.04864092,  4.06294707,
        4.07725322,  4.09155937,  4.10586552,  4.12017167,  4.13447783,
        4.14878398,  4.16309013,  4.17739628,  4.19170243,  4.20600858,
        4.22031474,  4.23462089,  4.24892704,  4.26323319,  4.27753934,
        4.29184549,  4.30615165,  4.3204578 ,  4.33476395,  4.3490701 ,
        4.36337625,  4.3776824 ,  4.39198856,  4.40629471,  4.42060086,
        4.43490701,  4.44921316,  4.46351931,  4.47782546,  4.49213162,
        4.50643777,  4.52074392,  4.53505007,  4.54935622,  4.56366237,
        4.57796853,  4.59227468,  4.60658083,  4.62088698,  4.63519313,
        4.64949928,  4.66380544,  4.67811159,  4.69241774,  4.70672389,
        4.72103004,  4.73533619,  4.74964235,  4.7639485 ,  4.77825465,
        4.7925608 ,  4.80686695,  4.8211731 ,  4.83547926,  4.84978541,
        4.86409156,  4.87839771,  4.89270386,  4.90701001,  4.92131617,
        4.93562232,  4.94992847,  4.96423462,  4.97854077,  4.99284692,
        5.00715308,  5.02145923,  5.03576538,  5.05007153,  5.06437768,
        5.07868383,  5.09298999,  5.10729614,  5.12160229,  5.13590844,
        5.15021459,  5.16452074,  5.1788269 ,  5.19313305,  5.2074392 ,
        5.22174535,  5.2360515 ,  5.25035765,  5.26466381,  5.27896996,
        5.29327611,  5.30758226,  5.32188841,  5.33619456,  5.35050072,
        5.36480687,  5.37911302,  5.39341917,  5.40772532,  5.42203147,
        5.43633763,  5.45064378,  5.46494993,  5.47925608,  5.49356223,
        5.50786838,  5.52217454,  5.53648069,  5.55078684,  5.56509299,
        5.57939914,  5.59370529,  5.60801144,  5.6223176 ,  5.63662375,
        5.6509299 ,  5.66523605,  5.6795422 ,  5.69384835,  5.70815451,
        5.72246066,  5.73676681,  5.75107296,  5.76537911,  5.77968526,
        5.79399142,  5.80829757,  5.82260372,  5.83690987,  5.85121602,
        5.86552217,  5.87982833,  5.89413448,  5.90844063,  5.92274678,
        5.93705293,  5.95135908,  5.96566524,  5.97997139,  5.99427754,
        6.00858369,  6.02288984,  6.03719599,  6.05150215,  6.0658083 ,
        6.08011445,  6.0944206 ,  6.10872675,  6.1230329 ,  6.13733906,
        6.15164521,  6.16595136,  6.18025751,  6.19456366,  6.20886981,
        6.22317597,  6.23748212,  6.25178827,  6.26609442,  6.28040057,
        6.29470672,  6.30901288,  6.32331903,  6.33762518,  6.35193133,
        6.36623748,  6.38054363,  6.39484979,  6.40915594,  6.42346209,
        6.43776824,  6.45207439,  6.46638054,  6.4806867 ,  6.49499285,
        6.509299  ,  6.52360515,  6.5379113 ,  6.55221745,  6.56652361,
        6.58082976,  6.59513591,  6.60944206,  6.62374821,  6.63805436,
        6.65236052,  6.66666667,  6.68097282,  6.69527897,  6.70958512,
        6.72389127,  6.73819742,  6.75250358,  6.76680973,  6.78111588,
        6.79542203,  6.80972818,  6.82403433,  6.83834049,  6.85264664,
        6.86695279,  6.88125894,  6.89556509,  6.90987124,  6.9241774 ,
        6.93848355,  6.9527897 ,  6.96709585,  6.981402  ,  6.99570815,
        7.01001431,  7.02432046,  7.03862661,  7.05293276,  7.06723891,
        7.08154506,  7.09585122,  7.11015737,  7.12446352,  7.13876967,
        7.15307582,  7.16738197,  7.18168813,  7.19599428,  7.21030043,
        7.22460658,  7.23891273,  7.25321888,  7.26752504,  7.28183119,
        7.29613734,  7.31044349,  7.32474964,  7.33905579,  7.35336195,
        7.3676681 ,  7.38197425,  7.3962804 ,  7.41058655,  7.4248927 ,
        7.43919886,  7.45350501,  7.46781116,  7.48211731,  7.49642346,
        7.51072961,  7.52503577,  7.53934192,  7.55364807,  7.56795422,
        7.58226037,  7.59656652,  7.61087268,  7.62517883,  7.63948498,
        7.65379113,  7.66809728,  7.68240343,  7.69670959,  7.71101574,
        7.72532189,  7.73962804,  7.75393419,  7.76824034,  7.78254649,
        7.79685265,  7.8111588 ,  7.82546495,  7.8397711 ,  7.85407725,
        7.8683834 ,  7.88268956,  7.89699571,  7.91130186,  7.92560801,
        7.93991416,  7.95422031,  7.96852647,  7.98283262,  7.99713877,
        8.01144492,  8.02575107,  8.04005722,  8.05436338,  8.06866953,
        8.08297568,  8.09728183,  8.11158798,  8.12589413,  8.14020029,
        8.15450644,  8.16881259,  8.18311874,  8.19742489,  8.21173104,
        8.2260372 ,  8.24034335,  8.2546495 ,  8.26895565,  8.2832618 ,
        8.29756795,  8.31187411,  8.32618026,  8.34048641,  8.35479256,
        8.36909871,  8.38340486,  8.39771102,  8.41201717,  8.42632332,
        8.44062947,  8.45493562,  8.46924177,  8.48354793,  8.49785408,
        8.51216023,  8.52646638,  8.54077253,  8.55507868,  8.56938484,
        8.58369099,  8.59799714,  8.61230329,  8.62660944,  8.64091559,
        8.65522175,  8.6695279 ,  8.68383405,  8.6981402 ,  8.71244635,
        8.7267525 ,  8.74105866,  8.75536481,  8.76967096,  8.78397711,
        8.79828326,  8.81258941,  8.82689557,  8.84120172,  8.85550787,
        8.86981402,  8.88412017,  8.89842632,  8.91273247,  8.92703863,
        8.94134478,  8.95565093,  8.96995708,  8.98426323,  8.99856938,
        9.01287554,  9.02718169,  9.04148784,  9.05579399,  9.07010014,
        9.08440629,  9.09871245,  9.1130186 ,  9.12732475,  9.1416309 ,
        9.15593705,  9.1702432 ,  9.18454936,  9.19885551,  9.21316166,
        9.22746781,  9.24177396,  9.25608011,  9.27038627,  9.28469242,
        9.29899857,  9.31330472,  9.32761087,  9.34191702,  9.35622318,
        9.37052933,  9.38483548,  9.39914163,  9.41344778,  9.42775393,
        9.44206009,  9.45636624,  9.47067239,  9.48497854,  9.49928469,
        9.51359084,  9.527897  ,  9.54220315,  9.5565093 ,  9.57081545,
        9.5851216 ,  9.59942775,  9.61373391,  9.62804006,  9.64234621,
        9.65665236,  9.67095851,  9.68526466,  9.69957082,  9.71387697,
        9.72818312,  9.74248927,  9.75679542,  9.77110157,  9.78540773,
        9.79971388,  9.81402003,  9.82832618,  9.84263233,  9.85693848,
        9.87124464,  9.88555079,  9.89985694,  9.91416309,  9.92846924,
        9.94277539,  9.95708155,  9.9713877 ,  9.98569385, 10.        ])

In [ ]:
p.full(full_array = nusage_array.shape, 60)
full_array

array([60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
       60, 60, 60])

In [ ]:
usage_array

array([393., 268., 154., 239., 187.,  99., 350., 543., 340., 424.,  53.,
       215., 462., 215., 189., 503., 132., 299.,  81., 577.,  93., 576.,
       423., 292., 216.,  91., 444., 512., 452., 412., 260., 197., 278.,
        46., 593.,  32., 122., 522., 473., 398., 240., 576., 120., 152.,
       138., 502., 558., 138., 580.,  nan,  nan,  nan,  nan,  97., 516.,
        68.,  64., 539., 428., 325., 522., 309.,  79., 545., 459., 225.,
       257., 134., 516.,  82., 452., 521., 457.,  31.,  47., 229.,  34.,
       173.,  78., 230., 565., 172., 330.,  39., 223., 404., 151.,  34.,
       137., 301., 116., 291.,  84., 134., 411., 326., 550., 516.,  59.,
       225.,  41., 183., 174., 274., 166.,  66., 152.,  54., 187., 216.,
        95., 488., 295., 136., 471., 121.,  75., 220.,  82.,  97., 388.,
       529., 584., 529., 227., 535., 332., 252., 125.,  97., 540., 320.,
       176.,  79.,  83., 555.,  66., 237., 497., 516., 219., 448., 156.,
        68., 524., 188., 443.,  52., 228., 149., 523.,  42., 120., 329.,
        68., 158.,  86., 339., 304., 131.,  64.,  53., 442.,  32., 278.,
       540., 595.,  35., 225., 587.,  92.,  46., 153., 368.,  51., 279.,
       255., 193., 207., 539., 151., 474., 544.,  nan, 597., 498., 402.,
        75., 130.,  42., 134.,  79., 432., 262., 473., 202., 215., 151.,
        80., 126., 495., 127.,  88.,  69., 100., 301.,  78., 163., 539.,
       278., 451., 481., 133.,  41., 152., 553., 402., 555., 499., 101.,
       433., 133., 351., 532.,  92., 511., 384., 193., 132., 360., 159.,
       495., 537., 129., 132.,  37., 524., 425.,  64., 573.,  45., 564.,
       162., 451.,  30., 202.,  71., 314., 168.,  75.,  42., 441., 523.,
       100.,  52., 397., 424., 272., 201., 570.,  64., 334., 518.,  70.,
       334., 563., 181., 584., 208., 381., 426., 284., 105., 179., 122.,
       501., 269., 230.,  85., 411.,  73.,  39., 386.,  49., 411., 534.,
       314., 211., 121.,  84., 448.,  55.,  59., 226., 580.,  65., 458.,
       170., 264., 122., 420., 267., 469., 541., 155., 106., 243., 410.,
       285., 397., 230., 341., 132., 130., 281.,  74., 299., 116., 408.,
       508., 227., 274., 347.,  76., 445., 203., 199.,  48.,  88., 541.,
       233., 176., 191., 461.,  37., 531., 473.,  30., 306.,  64.,  75.,
       597., 529., 290., 256., 308., 156.,  62., 156., 303., 463.,  60.,
       225., 379.,  53.,  30., 291., 488.,  74., 230., 517., 557.,  78.,
       321., 579., 382., 516., 598., 102., 165., 558., 561., 511., 560.,
        69.,  44.,  65., 458., 525., 106., 188., 493.,  84., 104., 102.,
       349.,  98.,  72., 563., 119., 311., 337., 168., 331., 589., 472.,
        78., 517.,  41.,  49., 522.,  97., 411., 566., 559., 478., 147.,
       395., 357., 405., 501., 575., 257., 270., 116.,  98., 264., 572.,
       202.,  83.,  32., 168., 416.,  46., 201., 130.,  98., 105.,  94.,
       540., 266., 140., 534.,  46., 581., 105., 221.,  41., 105., 123.,
       260., 223.,  66., 231., 555., 378., 546., 234., 152.,  34., 179.,
       591., 120.,  88., 143.,  74.,  74., 234.,  56., 174., 523., 123.,
       216., 290.,  68., 265., 414., 238., 429.,  39., 248., 541., 139.,
       289., 210., 412., 318., 258., 258., 189., 155., 528., 549.,  78.,
       444.,  80., 131., 228., 416., 586., 416., 152.,  87., 329., 107.,
       493., 182., 102., 274., 143.,  66., 420., 582., 200., 493., 348.,
       238.,  33., 267., 492., 241., 567.,  36., 110., 466., 126., 120.,
        64., 574., 119., 350.,  69., 438., 506., 272., 224.,  99.,  44.,
       175., 228., 589., 339., 431., 190., 389., 139., 289., 593., 576.,
       592., 567., 170., 242., 275., 544.,  50., 236., 139., 383., 172.,
       455., 157., 173., 405., 387., 201., 142., 198., 361., 553., 408.,
       121.,  71.,  46., 290.,  60., 116.,  86., 291., 404., 441., 444.,
       211., 537., 519.,  94., 554., 381., 257.,  47., 527., 148., 191.,
        71.,  73., 149., 197., 328., 424., 111., 159., 580., 379., 217.,
       447., 512., 511., 140., 114., 192., 325.,  83., 122., 138., 182.,
       425., 580., 203., 258., 551., 507.,  57., 553.,  49., 106., 119.,
       288., 225., 342., 292., 218.,  64., 453.,  42.,  36.,  55., 210.,
       227.,  47., 461.,  94., 216., 496., 138., 318.,  96., 510.,  83.,
       417., 538.,  63.,  50., 502., 105., 186., 174.,  89.,  66., 389.,
       186., 149.,  69., 206.,  49., 594., 104., 262., 278., 463., 505.,
        50., 138., 130., 469., 555., 198., 529., 205., 170., 160.,  81.,
       468., 500.,  37., 522.,  81., 141., 115., 298.,  33., 307., 380.,
       190.,  75., 218., 412., 335., 387., 261., 541., 195., 178., 378.,
       505., 564.,  92., 316.,  99.,  62., 212.])

In [ ]:
eye_matrix = np.eye(len(usage_array))
eye_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
empty_array = np.empty(usage_array.shape)
empty_array

array([0.00000000e+000, 2.12199590e-314, 0.00000000e+000, 1.04247851e-321,
       2.14321575e-312, 2.12199579e-314, 2.97079411e-313, 7.90505033e-323,
       0.00000000e+000, 6.36598743e-314, 2.12199579e-314, 4.66839074e-313,
       0.00000000e+000, 2.14321575e-312, 2.12199579e-314, 4.88059032e-313,
       1.67982320e-322, 0.00000000e+000, 1.27319748e-313, 2.12199579e-314,
       8.48798316e-313, 0.00000000e+000, 3.62861280e-312, 2.12199579e-314,
       2.97079411e-313, 2.02566915e-322, 0.00000000e+000, 8.48798321e-314,
       2.12199579e-314, 2.33419537e-313, 0.00000000e+000, 2.12199579e-312,
                   nan,             nan, 2.12199579e-314, 0.00000000e+000,
       4.10074486e-322,             nan,             nan, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.14587876e-314, 2.67882273e-314, 2.14587903e-314,
       2.14587881e-314, 2.14587895e-314, 2.14587893e-314, 2.14587708e-314,
       2.14587867e-314, 2.14587895e-314, 2.14587890e-314, 2.14587898e-314,
       2.14587888e-314, 2.14587871e-314, 2.14587907e-314, 2.14587871e-314,
       2.14587905e-314, 2.14587736e-314, 2.14587656e-314, 2.14587708e-314,
       2.14587708e-314, 2.14587708e-314, 2.14587708e-314, 2.14587715e-314,
       2.14587708e-314, 2.14587862e-314, 2.14587905e-314, 2.14587708e-314,
       2.14587907e-314, 2.14587879e-314, 2.14587862e-314, 2.14587907e-314,
       2.14587708e-314, 2.14587902e-314, 2.14587871e-314, 2.14587905e-314,
       2.14587898e-314, 2.14587895e-314, 2.14587893e-314, 2.14587905e-314,
       2.14587871e-314, 2.14587708e-314, 2.14587914e-314, 2.14587881e-314,
       2.14587888e-314, 2.14587888e-314, 2.14587708e-314, 2.14587864e-314,
       2.14587871e-314, 2.14587708e-314, 2.14587905e-314, 2.14587871e-314,
       2.14587893e-314, 2.14587907e-314, 2.14587708e-314, 2.14587874e-314,
       2.14587902e-314, 2.14587895e-314, 2.14587890e-314, 2.14587708e-314,
       2.14587862e-314, 2.14587708e-314, 2.14587864e-314, 2.14587876e-314,
       2.14587708e-314, 2.14587907e-314, 2.14587879e-314, 2.14587902e-314,
       2.14587871e-314, 2.14587862e-314, 2.14587869e-314, 2.14587741e-314,
       2.14587656e-314, 2.14587708e-314, 2.14587708e-314, 2.14587708e-314,
       2.14587708e-314, 2.14587895e-314, 2.14587909e-314, 2.14587907e-314,
       2.14587898e-314, 2.14587909e-314, 2.14587907e-314, 2.14587708e-314,
       2.14587777e-314, 2.14587708e-314, 2.14587869e-314, 2.14587881e-314,
       2.14587905e-314, 2.14587898e-314, 2.14587888e-314, 2.14587862e-314,
       2.14587919e-314, 2.14587727e-314, 2.14587924e-314, 2.14587713e-314,
       2.14587862e-314, 2.14587898e-314, 2.14587898e-314, 2.14587888e-314,
       2.14587881e-314, 2.14587867e-314, 2.14587862e-314, 2.14587907e-314,
       2.14587881e-314, 2.14587895e-314, 2.14587893e-314, 2.14587743e-314,
       2.14587912e-314, 2.14587893e-314, 2.14587869e-314, 2.14587741e-314,
       2.14587912e-314, 2.14587905e-314, 2.14587867e-314, 2.14587895e-314,
       2.14587869e-314, 2.14587871e-314, 2.14587741e-314, 2.14587864e-314,
       2.14587876e-314, 2.14587741e-314, 2.14587871e-314, 2.14587917e-314,
       2.14587871e-314, 2.14587867e-314, 2.14587909e-314, 2.14587907e-314,
       2.14587881e-314, 2.14587895e-314, 2.14587893e-314, 2.14587741e-314,
       2.14587751e-314, 2.14587755e-314, 2.14587751e-314, 2.14587713e-314,
       2.58174147e-314, 2.58174147e-314, 2.14587708e-314, 2.14587708e-314,
       2.14587708e-314, 2.14587708e-314, 2.14587708e-314, 2.14587708e-314,
       2.14587708e-314, 2.14587708e-314, 2.14587708e-314, 2.14587708e-314,
       2.14587708e-314, 2.14587895e-314, 2.14587909e-314, 2.14587907e-314,
       2.14587898e-314, 2.14587909e-314, 2.14587907e-314, 2.14587741e-314,
       2.14587909e-314, 2.14587898e-314, 2.14587869e-314, 2.14587862e-314,
       1.58714116e-047, 3.67152085e-062, 1.03914857e-095, 5.05347768e-038,
       8.41799477e-053, 2.11142223e-052, 2.00253744e-052, 1.14615574e-259,
       6.01347002e-154, 1.10978642e-047, 3.67152085e-062, 8.51516457e-096,
       3.06247023e-057, 8.41799496e-053, 5.15249986e-062, 7.48536278e-067,
       1.14694782e-259, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [ ]:
# Imagine we don't have real ratings yet
np.random.seed(42)   # Fix seed for reproducibility

# Create fake random movie ratings (scale 1–5) for 5 movies
random_ratings = np.random.randint(1, 6, size=5)
movies = ["Inception", "Interstellar", "Avatar", "Titanic", "The Matrix"]

# Pick top 3 movies based on fake random ratings
top_movies_test = [movie for _, movie in sorted(zip(random_ratings, movies),
                                               reverse=True)][:3]

print("🎯 Testing Phase")
print("Fake Random Ratings:", dict(zip(movies, random_ratings)))
print("Top 3 Movies (Fake Data):", top_movies_test)

🎯 Testing Phase
Fake Random Ratings: {'Inception': 4, 'Interstellar': 5, 'Avatar': 3, 'Titanic': 5, 'The Matrix': 5}
Top 3 Movies (Fake Data): ['Titanic', 'The Matrix', 'Interstellar']

In [ ]:
# Example of real user ratings (collected later)
real_ratings = np.array([4.8, 4.6, 3.5, 4.9, 4.2])  # real averages from users

# Pick top 3 movies based on real ratings
top_movies_real = [movie for _, movie in sorted(zip(real_ratings, movies),
                                               reverse=True)][:3]

print("\n🚨 Production Phase")
print("Real User Ratings:", dict(zip(movies, real_ratings)))
print("Top 3 Movies (Real Data):", top_movies_real)

🚨 Production Phase
Real User Ratings: {'Inception': 4.8, 'Interstellar': 4.6, 'Avatar': 3.5, 'Titanic': 4.9, 'The Matrix': 4.2}
Top 3 Movies (Real Data): ['Titanic', 'Inception', 'Interstellar']

In [ ]:
np.random.random((3,3))

array([[0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485]])

In [ ]:
np.random.rand(2,3)

array([[0.17052412, 0.06505159, 0.94888554],
       [0.96563203, 0.80839735, 0.30461377]])

array([[62, 14, 95],
       [48, 15, 72],
       [78, 87, 62]])

In [ ]:
np.random.randint(1,100, size =(3,3))

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print("Add:", a + b)

Add: [5 7 9]

In [ ]:
df['Screen On Time (min/day)'] = df['Screen On Time (hours/day)'] * 60
df['Screen On Time (min/day)']

0      384.0
1      282.0
2      240.0
3      288.0
4      258.0
       ...
695    234.0
696    408.0
697    186.0
698    102.0
699    324.0
Name: Screen On Time (min/day), Length: 700, dtype: float64

In [ ]:
df['Total Screen Time (min/day)'] = df['App Usage Time (min/day)'] + df['Screen On Time (min/day)']
df['Total Screen Time (min/day)']

0      777.0
1      550.0
2      394.0
3      527.0
4      445.0
       ...
695    326.0
696    724.0
697    285.0
698    164.0
699    536.0
Name: Total Screen Time (min/day), Length: 700, dtype: float64

In [ ]:
import numpy as np

# Create a 1-D array with 12 elements
arr = np.arange(12)
print("Original Array:\n", arr)
print("Shape:", arr.shape)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

In [ ]:

# Reshape to 3 rows × 4 columns
reshaped_arr = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped_arr)
print("New Shape:", reshaped_arr.shape)

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Shape: (3, 4)

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('/Users/rashmithav/Desktop/Desktop/datasets_dataminds/user_behavior_missing data-2.csv')

In [32]:
df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [33]:
reshaped_col = df['App Usage Time (min/day)'].to_numpy().reshape(-1,1)

In [34]:
reshaped_col

array([[393.],
       [268.],
       [154.],
       [239.],
       [187.],
       [ 99.],
       [350.],
       [543.],
       [340.],
       [424.],
       [ 53.],
       [215.],
       [462.],
       [215.],
       [189.],
       [503.],
       [132.],
       [299.],
       [ 81.],
       [577.],
       [ 93.],
       [576.],
       [423.],
       [292.],
       [216.],
       [ 91.],
       [444.],
       [512.],
       [452.],
       [412.],
       [260.],
       [197.],
       [278.],
       [ 46.],
       [593.],
       [ 32.],
       [122.],
       [522.],
       [473.],
       [398.],
       [240.],
       [576.],
       [120.],
       [152.],
       [138.],
       [502.],
       [558.],
       [138.],
       [580.],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ 97.],
       [516.],
       [ 68.],
       [ 64.],
       [539.],
       [428.],
       [325.],
       [522.],
       [309.],
       [ 79.],
       [545.],
       [459.],
       [225.],
       [257.],
       [134.],
       [516.],
       [ 82.],
       [452.],
       [521.],
       [457.],
       [ 31.],
       [ 47.],
       [229.],
       [ 34.],
       [173.],
       [ 78.],
       [230.],
       [565.],
       [172.],
       [330.],
       [ 39.],
       [223.],
       [404.],
       [151.],
       [ 34.],
       [137.],
       [301.],
       [116.],
       [291.],
       [ 84.],
       [134.],
       [411.],
       [326.],
       [550.],
       [516.],
       [ 59.],
       [225.],
       [ 41.],
       [183.],
       [174.],
       [274.],
       [166.],
       [ 66.],
       [152.],
       [ 54.],
       [187.],
       [216.],
       [ 95.],
       [488.],
       [295.],
       [136.],
       [471.],
       [121.],
       [ 75.],
       [220.],
       [ 82.],
       [ 97.],
       [388.],
       [529.],
       [584.],
       [529.],
       [227.],
       [535.],
       [332.],
       [252.],
       [125.],
       [ 97.],
       [540.],
       [320.],
       [176.],
       [ 79.],
       [ 83.],
       [555.],
       [ 66.],
       [237.],
       [497.],
       [516.],
       [219.],
       [448.],
       [156.],
       [ 68.],
       [524.],
       [188.],
       [443.],
       [ 52.],
       [228.],
       [149.],
       [523.],
       [ 42.],
       [120.],
       [329.],
       [ 68.],
       [158.],
       [ 86.],
       [339.],
       [304.],
       [131.],
       [ 64.],
       [ 53.],
       [442.],
       [ 32.],
       [278.],
       [540.],
       [595.],
       [ 35.],
       [225.],
       [587.],
       [ 92.],
       [ 46.],
       [153.],
       [368.],
       [ 51.],
       [279.],
       [255.],
       [193.],
       [207.],
       [539.],
       [151.],
       [474.],
       [544.],
       [ nan],
       [597.],
       [498.],
       [402.],
       [ 75.],
       [130.],
       [ 42.],
       [134.],
       [ 79.],
       [432.],
       [262.],
       [473.],
       [202.],
       [215.],
       [151.],
       [ 80.],
       [126.],
       [495.],
       [127.],
       [ 88.],
       [ 69.],
       [100.],
       [301.],
       [ 78.],
       [163.],
       [539.],
       [278.],
       [451.],
       [481.],
       [133.],
       [ 41.],
       [152.],
       [553.],
       [402.],
       [555.],
       [499.],
       [101.],
       [433.],
       [133.],
       [351.],
       [532.],
       [ 92.],
       [511.],
       [384.],
       [193.],
       [132.],
       [360.],
       [159.],
       [495.],
       [537.],
       [129.],
       [132.],
       [ 37.],
       [524.],
       [425.],
       [ 64.],
       [573.],
       [ 45.],
       [564.],
       [162.],
       [451.],
       [ 30.],
       [202.],
       [ 71.],
       [314.],
       [168.],
       [ 75.],
       [ 42.],
       [441.],
       [523.],
       [100.],
       [ 52.],
       [397.],
       [424.],
       [272.],
       [201.],
       [570.],
       [ 64.],
       [334.],
       [518.],
       [ 70.],
       [334.],
       [563.],
       [181.],
       [584.],
       [208.],
       [381.],
       [426.],
       [284.],
       [105.],
       [179.],
       [122.],
       [501.],
       [269.],
       [230.],
       [ 85.],
       [411.],
       [ 73.],
       [ 39.],
       [386.],
       [ 49.],
       [411.],
       [534.],
       [314.],
       [211.],
       [121.],
       [ 84.],
       [448.],
       [ 55.],
       [ 59.],
       [226.],
       [580.],
       [ 65.],
       [458.],
       [170.],
       [264.],
       [122.],
       [420.],
       [267.],
       [469.],
       [541.],
       [155.],
       [106.],
       [243.],
       [410.],
       [285.],
       [397.],
       [230.],
       [341.],
       [132.],
       [130.],
       [281.],
       [ 74.],
       [299.],
       [116.],
       [408.],
       [508.],
       [227.],
       [274.],
       [347.],
       [ 76.],
       [445.],
       [203.],
       [199.],
       [ 48.],
       [ 88.],
       [541.],
       [233.],
       [176.],
       [191.],
       [461.],
       [ 37.],
       [531.],
       [473.],
       [ 30.],
       [306.],
       [ 64.],
       [ 75.],
       [597.],
       [529.],
       [290.],
       [256.],
       [308.],
       [156.],
       [ 62.],
       [156.],
       [303.],
       [463.],
       [ 60.],
       [225.],
       [379.],
       [ 53.],
       [ 30.],
       [291.],
       [488.],
       [ 74.],
       [230.],
       [517.],
       [557.],
       [ 78.],
       [321.],
       [579.],
       [382.],
       [516.],
       [598.],
       [102.],
       [165.],
       [558.],
       [561.],
       [511.],
       [560.],
       [ 69.],
       [ 44.],
       [ 65.],
       [458.],
       [525.],
       [106.],
       [188.],
       [493.],
       [ 84.],
       [104.],
       [102.],
       [349.],
       [ 98.],
       [ 72.],
       [563.],
       [119.],
       [311.],
       [337.],
       [168.],
       [331.],
       [589.],
       [472.],
       [ 78.],
       [517.],
       [ 41.],
       [ 49.],
       [522.],
       [ 97.],
       [411.],
       [566.],
       [559.],
       [478.],
       [147.],
       [395.],
       [357.],
       [405.],
       [501.],
       [575.],
       [257.],
       [270.],
       [116.],
       [ 98.],
       [264.],
       [572.],
       [202.],
       [ 83.],
       [ 32.],
       [168.],
       [416.],
       [ 46.],
       [201.],
       [130.],
       [ 98.],
       [105.],
       [ 94.],
       [540.],
       [266.],
       [140.],
       [534.],
       [ 46.],
       [581.],
       [105.],
       [221.],
       [ 41.],
       [105.],
       [123.],
       [260.],
       [223.],
       [ 66.],
       [231.],
       [555.],
       [378.],
       [546.],
       [234.],
       [152.],
       [ 34.],
       [179.],
       [591.],
       [120.],
       [ 88.],
       [143.],
       [ 74.],
       [ 74.],
       [234.],
       [ 56.],
       [174.],
       [523.],
       [123.],
       [216.],
       [290.],
       [ 68.],
       [265.],
       [414.],
       [238.],
       [429.],
       [ 39.],
       [248.],
       [541.],
       [139.],
       [289.],
       [210.],
       [412.],
       [318.],
       [258.],
       [258.],
       [189.],
       [155.],
       [528.],
       [549.],
       [ 78.],
       [444.],
       [ 80.],
       [131.],
       [228.],
       [416.],
       [586.],
       [416.],
       [152.],
       [ 87.],
       [329.],
       [107.],
       [493.],
       [182.],
       [102.],
       [274.],
       [143.],
       [ 66.],
       [420.],
       [582.],
       [200.],
       [493.],
       [348.],
       [238.],
       [ 33.],
       [267.],
       [492.],
       [241.],
       [567.],
       [ 36.],
       [110.],
       [466.],
       [126.],
       [120.],
       [ 64.],
       [574.],
       [119.],
       [350.],
       [ 69.],
       [438.],
       [506.],
       [272.],
       [224.],
       [ 99.],
       [ 44.],
       [175.],
       [228.],
       [589.],
       [339.],
       [431.],
       [190.],
       [389.],
       [139.],
       [289.],
       [593.],
       [576.],
       [592.],
       [567.],
       [170.],
       [242.],
       [275.],
       [544.],
       [ 50.],
       [236.],
       [139.],
       [383.],
       [172.],
       [455.],
       [157.],
       [173.],
       [405.],
       [387.],
       [201.],
       [142.],
       [198.],
       [361.],
       [553.],
       [408.],
       [121.],
       [ 71.],
       [ 46.],
       [290.],
       [ 60.],
       [116.],
       [ 86.],
       [291.],
       [404.],
       [441.],
       [444.],
       [211.],
       [537.],
       [519.],
       [ 94.],
       [554.],
       [381.],
       [257.],
       [ 47.],
       [527.],
       [148.],
       [191.],
       [ 71.],
       [ 73.],
       [149.],
       [197.],
       [328.],
       [424.],
       [111.],
       [159.],
       [580.],
       [379.],
       [217.],
       [447.],
       [512.],
       [511.],
       [140.],
       [114.],
       [192.],
       [325.],
       [ 83.],
       [122.],
       [138.],
       [182.],
       [425.],
       [580.],
       [203.],
       [258.],
       [551.],
       [507.],
       [ 57.],
       [553.],
       [ 49.],
       [106.],
       [119.],
       [288.],
       [225.],
       [342.],
       [292.],
       [218.],
       [ 64.],
       [453.],
       [ 42.],
       [ 36.],
       [ 55.],
       [210.],
       [227.],
       [ 47.],
       [461.],
       [ 94.],
       [216.],
       [496.],
       [138.],
       [318.],
       [ 96.],
       [510.],
       [ 83.],
       [417.],
       [538.],
       [ 63.],
       [ 50.],
       [502.],
       [105.],
       [186.],
       [174.],
       [ 89.],
       [ 66.],
       [389.],
       [186.],
       [149.],
       [ 69.],
       [206.],
       [ 49.],
       [594.],
       [104.],
       [262.],
       [278.],
       [463.],
       [505.],
       [ 50.],
       [138.],
       [130.],
       [469.],
       [555.],
       [198.],
       [529.],
       [205.],
       [170.],
       [160.],
       [ 81.],
       [468.],
       [500.],
       [ 37.],
       [522.],
       [ 81.],
       [141.],
       [115.],
       [298.],
       [ 33.],
       [307.],
       [380.],
       [190.],
       [ 75.],
       [218.],
       [412.],
       [335.],
       [387.],
       [261.],
       [541.],
       [195.],
       [178.],
       [378.],
       [505.],
       [564.],
       [ 92.],
       [316.],
       [ 99.],
       [ 62.],
       [212.]])

In [35]:
data = [23,1,45,12,67,34,89]
data.sort()
data

[1, 12, 23, 34, 45, 67, 89]

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [37]:
arr.shape

(2, 3)

In [38]:
arr.size

6

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr.itemsize

8

In [41]:
arr.nbytes

48

In [42]:
df['App Usage Time (min/day)']

0      393.0
1      268.0
2      154.0
3      239.0
4      187.0
       ...
695     92.0
696    316.0
697     99.0
698     62.0
699    212.0
Name: App Usage Time (min/day), Length: 700, dtype: float64

In [44]:
df[1 : 3]

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2

In [45]:
# loc - label based indexing 
df.loc[2]

User ID                                  3
Device Model                  Xiaomi Mi 11
Operating System                   Android
App Usage Time (min/day)             154.0
Screen On Time (hours/day)             4.0
Battery Drain (mAh/day)              761.0
Number of Apps Installed              32.0
Data Usage (MB/day)                    322
Age                                     42
Gender                                 NaN
User Behavior Class                      2
Name: 2, dtype: object

In [48]:
df.loc[5: 10]

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
5,6,Google Pixel 5,NaN,99.0,2.0,940.0,35.0,564,31,NaN,2
6,7,Samsung Galaxy S21,Android,350.0,7.3,1802.0,66.0,1054,21,Female,4
7,8,OnePlus 9,Android,543.0,11.4,2956.0,82.0,1702,31,Male,5
8,9,Samsung Galaxy S21,Android,340.0,7.7,2138.0,75.0,1053,42,Female,4
9,10,iPhone 12,iOS,424.0,6.6,1957.0,75.0,1301,42,NaN,4
10,11,Google Pixel 5,Android,53.0,1.4,435.0,17.0,162,34,Female,1

In [49]:
df.loc[1,'App Usage Time (min/day)']

268.0

In [50]:
df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [51]:
df.loc[:, ['User ID','Gender','Data Usage (MB/day)']]

     User ID  Gender  Data Usage (MB/day)
0          1    Male                 1122
1          2  Female                  944
2          3     NaN                  322
3          4     NaN                  871
4          5  Female                  988
..       ...     ...                  ...
695      696    Male                  381
696      697    Male                 1201
697      698  Female                  457
698      699    Male                  224
699      700  Female                  828

[700 rows x 3 columns]

In [52]:
df.iloc[0]

User ID                                    1
Device Model                  Google Pixel 5
Operating System                     Android
App Usage Time (min/day)               393.0
Screen On Time (hours/day)               6.4
Battery Drain (mAh/day)               1872.0
Number of Apps Installed                67.0
Data Usage (MB/day)                     1122
Age                                       40
Gender                                  Male
User Behavior Class                        4
Name: 0, dtype: object

In [53]:
df.iloc[0:3]

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2

In [56]:
df.iloc[1,3]

268.0

In [58]:
df.iloc[: ,[0,7,5]]

     User ID  Data Usage (MB/day)  Battery Drain (mAh/day)
0          1                 1122                   1872.0
1          2                  944                   1331.0
2          3                  322                    761.0
3          4                  871                   1676.0
4          5                  988                   1367.0
..       ...                  ...                      ...
695      696                  381                   1082.0
696      697                 1201                   1965.0
697      698                  457                    942.0
698      699                  224                    431.0
699      700                  828                   1306.0

[700 rows x 3 columns]

In [59]:
df

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN,3
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female,3
...,...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male,4
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male,1
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female,3

In [60]:
x = df.iloc[ : , :-1]
x

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female
...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female

In [61]:
y = df.iloc[ : ,-1]
y

0      4
1      3
2      2
3      3
4      3
      ..
695    2
696    4
697    2
698    1
699    3
Name: User Behavior Class, Length: 700, dtype: int64

In [62]:
x

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female
...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female

In [63]:
y

0      4
1      3
2      2
3      3
4      3
      ..
695    2
696    4
697    2
698    1
699    3
Name: User Behavior Class, Length: 700, dtype: int64

In [64]:
x = df.iloc[:, df.columns != df.columns[3]]
x

,User ID,Device Model,Operating System,Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,4.0,761.0,32.0,322,42,NaN,2
3,4,Google Pixel 5,Android,4.8,1676.0,56.0,871,20,NaN,3
4,5,iPhone 12,iOS,4.3,1367.0,58.0,988,31,Female,3
...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,3.9,1082.0,26.0,381,22,Male,2
696,697,Xiaomi Mi 11,Android,6.8,1965.0,68.0,1201,59,Male,4
697,698,Google Pixel 5,Android,3.1,942.0,22.0,457,50,Female,2
698,699,Samsung Galaxy S21,Android,1.7,431.0,13.0,224,44,Male,1
699,700,OnePlus 9,Android,5.4,1306.0,49.0,828,23,Female,3

In [66]:
y = df.iloc[:, 3]
y

0      393.0
1      268.0
2      154.0
3      239.0
4      187.0
       ...
695     92.0
696    316.0
697     99.0
698     62.0
699    212.0
Name: App Usage Time (min/day), Length: 700, dtype: float64

#### **Real time example:**
## **Where we need to analyze sales data for different products across several months.**

In [ ]:
# Step 1: Sales data for 3 products across 6 months
import numpy as np
sales_data = {
    'Product_A': np.array([250, 300, 400, 500, 600, 700]),
    'Product_B': np.array([150, 200, 250, 300, 350, 400]),
    'Product_C': np.array([100, 150, 200, 250, 300, 350])
}

In [68]:
# Step 2: Calculate total sales for each product
total_sales = {product: np.sum(sales) for product, sales in sales_data.items()}
total_sales

{'Product_A': 2750, 'Product_B': 1650, 'Product_C': 1350}

In [70]:
# Step 3: Calculate average monthly sales for each product
average_sales = {product: np.mean(sales) for product, sales in sales_data.items()}
average_sales

{'Product_A': 458.3333333333333, 'Product_B': 275.0, 'Product_C': 225.0}

In [73]:
# Step 4: Find the product with highest sales in 4th month (April-like case)
month_index = 3  # 0-based index (0 = Jan, 1 = Feb, 2 = Mar, 3 = Apr)
sales_in_fourth_month = {product: sales[month_index] for product, sales in sales_data.items()}
highest_sales_product = max(sales_in_fourth_month, key=sales_in_fourth_month.get)
sales_in_fourth_month 
highest_sales_product

'Product_A'

In [74]:
# Step 5: Print the output in readable format
print("📊 Total Sales per Product:")
for product, total in total_sales.items():
    print(f"{product}: {total} units")

print("\n📈 Average Monthly Sales:")
for product, avg in average_sales.items():
    print(f"{product}: {avg:.2f} units")

print("\n🏆 Highest Sales in 4th Month:")
print(f"{highest_sales_product} with {sales_in_fourth_month[highest_sales_product]} units sold")

📊 Total Sales per Product:
Product_A: 2750 units
Product_B: 1650 units
Product_C: 1350 units

📈 Average Monthly Sales:
Product_A: 458.33 units
Product_B: 275.00 units
Product_C: 225.00 units

🏆 Highest Sales in 4th Month:
Product_A with 500 units sold