In [5]:
# !pip install pandas
# %pip install pandas

In [6]:
import pandas as pd 
import numpy as np 
import os

In [7]:
# Lets try to write list first 
list1 = [ 200, 20.5, 'NAN']
type(list1)

list

- **`Pd.Series`**

In [8]:
# converting into pandas series 
pd_series = pd.Series(list1)
type(pd_series)

pandas.core.series.Series

In [9]:
print(pd_series) # converted into column

0     200
1    20.5
2     NAN
dtype: object

In [10]:

print(pd_series[1]) # shows index postion

20.5

- **`Pd.DataFrame`**

In [11]:
# 2️⃣ Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
    'Age': [25, 30, 35, np.nan, 28],
    'Salary': [50000, 60000, 70000, 80000, np.nan],
    'Department': ['HR', 'Finance', 'IT', 'IT', 'Finance'],
    'Joining_Date': ['2020-01-15', '2018-07-10', '2019-03-22', '2021-11-01', '2022-06-30']
}

df = pd.DataFrame(data)
df

      Name   Age   Salary Department Joining_Date
0    Alice  25.0  50000.0         HR   2020-01-15
1      Bob  30.0  60000.0    Finance   2018-07-10
2  Charlie  35.0  70000.0         IT   2019-03-22
3    Diana   NaN  80000.0         IT   2021-11-01
4     Evan  28.0      NaN    Finance   2022-06-30

In [12]:
# 3️⃣ Basic Exploration,Inspection & Selection

# Basic Information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Age           4 non-null      float64
 2   Salary        4 non-null      float64
 3   Department    5 non-null      object
 4   Joining_Date  5 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes

In [13]:
# Summary Statistics
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   29.500000  65000.000000
std     4.203173  12909.944487
min    25.000000  50000.000000
25%    27.250000  57500.000000
50%    29.000000  65000.000000
75%    31.250000  72500.000000
max    35.000000  80000.000000

In [14]:

#First 3 Rows
df.head(3)
df.tail()

      Name   Age   Salary Department Joining_Date
0    Alice  25.0  50000.0         HR   2020-01-15
1      Bob  30.0  60000.0    Finance   2018-07-10
2  Charlie  35.0  70000.0         IT   2019-03-22
3    Diana   NaN  80000.0         IT   2021-11-01
4     Evan  28.0      NaN    Finance   2022-06-30

In [15]:

# Unique Departments
df['Department'].unique()

# “These commands help us quickly understand what our dataset looks like — column types, missing values, and summary stats.”*

array(['HR', 'Finance', 'IT'], dtype=object)

In [16]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])

print(" DataFrame Created:")
df['Joining_Date']

 DataFrame Created:

0   2020-01-15
1   2018-07-10
2   2019-03-22
3   2021-11-01
4   2022-06-30
Name: Joining_Date, dtype: datetime64[ns]

In [17]:
# 5️⃣ Create new columns

today = pd.Timestamp('2025-11-04')   
df['Experience'] = (today - df['Joining_Date']).dt.days / 365
df['Experience']
# ➡️ Subtracts each employee’s Joining_Date from today. This gives a time difference (a pandas Timedelta object).

0    5.808219
1    7.326027
2    6.627397
3    4.010959
4    3.350685
Name: Experience, dtype: float64

In [18]:
# Add a new column: Salary category
df['Salary_Level'] = pd.cut(df['Salary'], bins=3, labels=['Low', 'Medium', 'High'])
print(df[['Name', 'Salary', 'Experience', 'Salary_Level']])

      Name   Salary  Experience Salary_Level
0    Alice  50000.0    5.808219          Low
1      Bob  60000.0    7.326027          Low
2  Charlie  70000.0    6.627397       Medium
3    Diana  80000.0    4.010959         High
4     Evan      NaN    3.350685          NaN

- **`GrouoBy`**

In [19]:
# Let’s start simple — find the average salary per department
avg_salary = df.groupby('Department')['Salary'].mean()
print("\nAverage Salary per Department:")
avg_salary

Average Salary per Department:

Department
Finance    60000.0
HR         50000.0
IT         75000.0
Name: Salary, dtype: float64

- **`Multiple Aggregations`**
- You can also apply multiple functions at once using .agg() — for example, average salary and total employees per department.

In [20]:
dept_summary = df.groupby('Department').agg({
    'Salary': ['mean', 'sum', 'max'],
    'Experience': ['mean', 'count']
})
print("\nDepartment Summary (Multiple Aggregations):")
dept_summary

Department Summary (Multiple Aggregations):

             Salary                    Experience
               mean       sum      max       mean count
Department
Finance     60000.0   60000.0  60000.0   5.338356     2
HR          50000.0   50000.0  50000.0   5.808219     1
IT          75000.0  150000.0  80000.0   5.319178     2

- **`Group By Multiple Columns`**

In [21]:
salary_by_dept_exp = df.groupby(['Department', 'Experience'])['Salary'].sum()
print("\nSalary Grouped by Department and Experience:")
salary_by_dept_exp

Salary Grouped by Department and Experience:

Department  Experience
Finance     3.350685          0.0
            7.326027      60000.0
HR          5.808219      50000.0
IT          4.010959      80000.0
            6.627397      70000.0
Name: Salary, dtype: float64

- **`Using groupby() with Filters`**

In [22]:
high_salary = df.groupby('Department')['Salary'].mean().reset_index()
high_salary = high_salary[high_salary['Salary'] > 60000]
print("\nDepartments with Average Salary > 60,000:")
print(high_salary)

Departments with Average Salary > 60,000:
  Department   Salary
2         IT  75000.0

In [23]:
# Importing Required Modules:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os            # 1.os for interacting with the operating system.
import pandas as pd   #2. pandas as pd for data manipulation.
import numpy as np
os.getcwd()   # 3.is used to print the current working directory.

'/Users/rashmithav/Documents/Dataminds/02. DMA_Batches/DSA132'

In [24]:
os.chdir('/Users/rashmithav/Documents/Dataminds/04. Datasets-Masters/Dataset-Master 1')

In [25]:
df = pd.read_csv('/Users/rashmithav/Documents/Dataminds/04. Datasets-Masters/Dataset-Master 1/VC_Startups.csv')
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10         NaN  192261.83
1   162597.70       151377.59        443898.53         NaN  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28              NaN     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35        NaN             NaN              NaN    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93              NaN    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [26]:
df1 = pd.read_excel('/Users/rashmithav/Documents/Dataminds/04. Datasets-Masters/Dataset-Master 1/weather_data.xlsx')
df1

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [27]:

df.to_json("/Users/rashmithav/Downloads/iris.json", index=False)
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10         NaN  192261.83
1   162597.70       151377.59        443898.53         NaN  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28              NaN     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35        NaN             NaN              NaN    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93              NaN    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [28]:





# his code saves our DataFrame into a JSON file, which is a lightweight format used for data sharing.
# JSON stores data in key–value pairs, just like a Python dictionary.
# So, when we write df.to_json(), we’re simply converting our table into a format that other programs — like web apps or APIs — can easily understand.”

# JSON = format to store and share data
# 🔹 df.to_json() = saves DataFrame as JSON file
# 🔹 Looks like dictionary-style data: { "Name": "Rashmitha", "City": "Hyderabad" }

In [29]:
import pandas as pd

# 1️⃣ Load the CSV file into a DataFrame
df = pd.read_csv('/Users/rashmithav/Documents/Dataminds/04. Datasets-Masters/Dataset-Master 1/VC_Startups.csv')

# 2️⃣ Remove the 'State' column and store it temporarily
state_col = df.pop('State')

# 3️⃣ Add the 'State' column back to the end of the DataFrame
df['State'] = state_col

# 4️⃣ Display the updated DataFrame
df.head()

   R&D Spend  Administration  Marketing Spend     Profit     State
0  165349.20       136897.80        471784.10  192261.83       NaN
1  162597.70       151377.59        443898.53  191792.06       NaN
2  153441.51       101145.55        407934.54  191050.39   Florida
3  144372.41       118671.85        383199.62  182901.99  New York
4  142107.34        91391.77        366168.42  166187.94   Florida

In [30]:
print(df.shape) # 1. Shape of the DataFrame
print(df.sample(2)) # 2. Random sample of 2 rows from the DataFrame
print(df.head(3)) # 3. First 3 rows of the DataFrame by default 5 rows
print(df.tail(2)) # 4. Last 2 rows of the DataFrame by default 5 rows
print(df.describe()) # 5. Descriptive statistics of the DataFrame only for numerical columns.(Five point summary)
print(df.columns)  # 6. Describe the Number of coloumn in DataFrame
print(df.dtypes)  #  7 . provide the type of data in dimentions
print(df.info()) # 8. Provides a summary of the DataFrame, showing the index, column names, non-null counts, and data types.

(50, 5)
    R&D Spend  Administration  Marketing Spend     Profit    State
1   162597.70       151377.59        443898.53  191792.06      NaN
12   93863.75       127320.38        249839.44  141585.52  Florida
   R&D Spend  Administration  Marketing Spend     Profit    State
0  165349.20       136897.80        471784.10  192261.83      NaN
1  162597.70       151377.59        443898.53  191792.06      NaN
2  153441.51       101145.55        407934.54  191050.39  Florida
    R&D Spend  Administration  Marketing Spend    Profit       State
48     542.05        51743.15             0.00  35673.41    New York
49       0.00       116983.80         45173.06  14681.40  California
           R&D Spend  Administration  Marketing Spend         Profit
count      49.000000       49.000000        47.000000      50.000000
mean    74287.076735   122085.398776    214241.295957  112012.639200
std     46201.655349    27809.055820    124868.319625   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     38558.510000   105751.030000    130883.445000   90138.902500
50%     73994.560000   122782.750000    229160.950000  107978.190000
75%    101913.080000   145077.580000    301528.275000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000
Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit', 'State'], dtype='object')
R&D Spend          float64
Administration     float64
Marketing Spend    float64
Profit             float64
State               object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        49 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  47 non-null     float64
 3   Profit           50 non-null     float64
 4   State            48 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None

In [31]:
# Let’s Create a Simple Time Series in Python
import pandas as pd

# Step 1: Create data
data = {
    'Date': ['2025-11-01', '2025-11-02', '2025-11-03', '2025-11-04'],
    'Sales': [50, 60, 45, 70]
}

# Step 2: Make a DataFrame
df = pd.DataFrame(data)
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4 non-null      object
 1   Sales   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

- **`Convert Date to “Date Format”`**

In [32]:
df['Date'] = pd.to_datetime(df['Date'])
print(df.dtypes)
# “Now Date is a datetime type — Python knows it’s a real calendar date!”
df['Date']

Date     datetime64[ns]
Sales             int64
dtype: object

0   2025-11-01
1   2025-11-02
2   2025-11-03
3   2025-11-04
Name: Date, dtype: datetime64[ns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4 non-null      datetime64[ns]
 1   Sales   4 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 196.0 bytes

In [34]:
# Set the Date as the Index (Timeline)
df.set_index('Date', inplace=True)
print(df)
# “See how ‘Date’ moved to the side? That means each row now sits on a timeline!”

            Sales
Date
2025-11-01     50
2025-11-02     60
2025-11-03     45
2025-11-04     70

- **`Analyze by Time`**
- Now we can easily ask questions like:
- What was the total weekly sales?
- What was the average per day?

In [35]:
# Total sales
print("Total:", df['Sales'].sum())

# Average daily sales
print("Average:", df['Sales'].mean())

Total: 225
Average: 56.25

- **`Resample (Group by Time)`**

In [36]:
# This will group data by week and sum up sales
weekly_sales = df['Sales'].resample('W').sum()
print(weekly_sales)

Date
2025-11-02    110
2025-11-09    115
Freq: W-SUN, Name: Sales, dtype: int64

- **`Extract Parts of Date`**

In [37]:
df['Month'] = df.index.month
df['Day_Name'] = df.index.day_name()
print(df)

            Sales  Month  Day_Name
Date
2025-11-01     50     11  Saturday
2025-11-02     60     11    Sunday
2025-11-03     45     11    Monday
2025-11-04     70     11   Tuesday

| Concept         | Meaning                       | Example                    |
| --------------- | ----------------------------- | -------------------------- |
| **Time Series** | Data arranged by time         | Daily sales, monthly bills |
| **DateTime**    | Python’s time-aware data type | ‘2025-11-04’               |
| **Set Index**   | Makes date your row label     | Easier for time math       |
| **Resample()**  | Group by time period          | Weekly, monthly            |
| **Rolling()**   | Moving average                | Smooth trends              |

- **`Small Practice for You`**
- Try this at home 👇
    - 1️⃣ Create a DataFrame for daily temperature for 10 days.
    - 2️⃣ Convert it to datetime type.
    - 3️⃣ Set date as index.
    - 4️⃣ Find average temperature.
    - 5️⃣ Resample weekly.


#### **What is Regular Expression (RegEx)?**

In [38]:
# You can use RegEx through the re module.
import re

text = "My email is data.minds@gmail.com"

# Find email pattern
pattern = r"\S+@\S+\.\S+"  # Rule for email
result = re.findall(pattern, text)
print(result)

# “Here, \S+ means one or more characters that aren’t spaces,
# and @ + . make sure it matches an email format!”

['data.minds@gmail.com']

In [39]:
import re
# Find all digits in text
text = "There are 3 cats and 12 dogs."
result = re.findall(r'\d+', text)
print(result)

['3', '12']

In [40]:
text = "cat, car, dog, cup, bat"
result = re.findall(r'c\w+', text)
print(result)
# r'c\w+' → finds all words that start with the letter ‘c’ followed by letters or numbers.

['cat', 'car', 'cup']

#### **`Common RegEx Patterns`**

| Pattern | Meaning                          | Example Match                   |
| ------- | -------------------------------- | ------------------------------- |
| `\d`    | Digit (0–9)                      | “123”                           |
| `\D`    | Non-digit                        | “abc”                           |
| `\w`    | Word character (letters/numbers) | “Hello123”                      |
| `\s`    | Space                            | “ ”                             |
| `.`     | Any character                    | “a”, “1”, “#”                   |
| `^`     | Starts with                      | `^Hello` → “Hello World”        |
| `$`     | Ends with                        | `world$` → “Hi world”           |
| `+`     | One or more                      | `\d+` → “12345”                 |
| `*`     | Zero or more                     | `go*` → “g”, “go”, “gooo”       |
| `?`     | Optional                         | `colou?r` → “color” or “colour” |



🧹 Real-Life Uses in Data Science

    ✅ Cleaning messy text (emails, phone numbers, IDs)
    ✅ Extracting patterns (like dates or hashtags)
    ✅ Validating input (like postal codes, PAN numbers)
    ✅ Tokenizing text for NLP

In [ ]:
import re

text = "My phone numbers are 9876543210 and 9123456789."

pattern = r"\d{10}"  # 10 digits in a row
numbers = re.findall(pattern, text)
print(numbers)
# See that? It picked only the 10-digit numbers! That’s the power of patterns!”

['9876543210']

### **Let me to show how RegEx is used inside pandas (for example — cleaning a DataFrame column using str.contains() or str.replace())**

In [42]:
import pandas as pd

data = {
    'Email': ['data.minds@gmail.com', 'hello_world@yahoo.com', 'contact@dataminds.in', 'test123@outlook.com'],
    'Message': ['Order ID: 12345', 'Refund ID: 54321', 'Order ID: 67890', 'Promo code: SAVE50']
}

df = pd.DataFrame(data)
print("Original Data:")
df

Original Data:

                   Email             Message
0   data.minds@gmail.com     Order ID: 12345
1  hello_world@yahoo.com    Refund ID: 54321
2   contact@dataminds.in     Order ID: 67890
3    test123@outlook.com  Promo code: SAVE50

- **`1: Using RegEx with str.contains()`**
- 👉 Goal: Find all rows where the message contains the word “Order”

In [43]:
order_rows = df[df['Message'].str.contains(r'Order', regex=True)]
print(order_rows)

                  Email          Message
0  data.minds@gmail.com  Order ID: 12345
2  contact@dataminds.in  Order ID: 67890

- **`2: Using RegEx with str.replace()`**
- 👉 Goal: Extract only the numeric Order IDs from the Message column

In [44]:
df['Order_Number'] = df['Message'].str.replace(r'\D', '', regex=True)
print(df)
# “\D means non-digit. So str.replace(r'\D', '', regex=True) removes everything except numbers.”

                   Email             Message Order_Number
0   data.minds@gmail.com     Order ID: 12345        12345
1  hello_world@yahoo.com    Refund ID: 54321        54321
2   contact@dataminds.in     Order ID: 67890        67890
3    test123@outlook.com  Promo code: SAVE50           50

- **`3: Extracting Patterns with str.extract()`**
- 👉 Goal: Pull out only the email domain names (like gmail.com, yahoo.com)

In [45]:
df['Domain'] = df['Email'].str.extract(r'@([\w\.]+)')
print(df[['Email', 'Domain']])

# “Here, @([\w\.]+) means:
# Find @,
# Then capture all letters, digits, underscores, and dots after it.”

                   Email        Domain
0   data.minds@gmail.com     gmail.com
1  hello_world@yahoo.com     yahoo.com
2   contact@dataminds.in  dataminds.in
3    test123@outlook.com   outlook.com

| Function         | Purpose                             | Example                          |
| ---------------- | ----------------------------------- | -------------------------------- |
| `str.contains()` | Filter rows by pattern              | Find emails containing ‘gmail’   |
| `str.replace()`  | Clean or remove unwanted characters | Remove special symbols           |
| `str.extract()`  | Capture specific pattern            | Extract domain, ID, or code      |
| `str.match()`    | Match entire string pattern         | Validate phone numbers           |
| `str.split()`    | Split text by pattern               | Split full names into first/last |

#### **`🎓 Quick Practice for You`**

Try to:

    1️⃣ Create a DataFrame with a column "Comments"
    2️⃣ Find all rows containing the word “error” (case-insensitive)
    3️⃣ Replace all numbers with #
    4️⃣ Extract any code pattern like "ERR1234"

### **`Extract Email Domain Names Using RegEx`**