In [69]:
import numpy as np
import pandas as pd
import scipy. stats as st

In [70]:
df = pd.read_csv('/Users/rashmithav/Desktop/Desktop/datasets_dataminds/user_behavior_missing data-2.csv')
df

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN,3
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female,3
...,...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male,4
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male,1
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female,3

In [71]:
df.isna()

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,False

In [72]:
df.isna().any()

User ID                       False
Device Model                  False
Operating System               True
App Usage Time (min/day)       True
Screen On Time (hours/day)     True
Battery Drain (mAh/day)        True
Number of Apps Installed       True
Data Usage (MB/day)           False
Age                           False
Gender                         True
User Behavior Class           False
dtype: bool

In [73]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              6
App Usage Time (min/day)      5
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        9
User Behavior Class           0
dtype: int64

In [74]:
df["Gender"].value_counts()

Gender
Male      357
Female    334
Name: count, dtype: int64

In [75]:
s = df["App Usage Time (min/day)"]

In [76]:
Mean = np.mean(s)
Mean

270.9438848920863

In [77]:
df.describe()

,User ID,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,User Behavior Class
count,700.00000,695.000000,691.000000,699.000000,699.000000,700.000000,700.000000,700.000000
mean,350.50000,270.943885,5.262952,1524.459227,50.623748,929.742857,38.482857,2.990000
std,202.21688,177.044617,3.068350,819.513827,26.919333,640.451729,12.012916,1.401476
min,1.00000,30.000000,1.000000,302.000000,10.000000,102.000000,18.000000,1.000000
25%,175.75000,112.500000,2.500000,721.500000,26.000000,373.000000,28.000000,2.000000
50%,350.50000,227.000000,4.900000,1500.000000,49.000000,823.500000,38.000000,3.000000
75%,525.25000,432.500000,7.400000,2230.000000,74.000000,1341.000000,49.000000,4.000000
max,700.00000,598.000000,12.000000,2993.000000,99.000000,2497.000000,59.000000,5.000000

In [78]:
Median= np.median(s)
Median

nan

In [79]:
mode_state = df["Gender"].mode()[0]
mode_state

'Male'

In [80]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              6
App Usage Time (min/day)      5
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        9
User Behavior Class           0
dtype: int64

In [81]:
df['App Usage Time (min/day)'].fillna(df['App Usage Time (min/day)'].mean,inplace = True)

/var/folders/td/x0tmvm6n1dn552__97jmrspr0000gn/T/ipykernel_15916/3234774701.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0      393.0
1      268.0
2      154.0
3      239.0
4      187.0
       ...
695     92.0
696    316.0
697     99.0
698     62.0
699    212.0
Name: App Usage Time (min/day), Length: 700, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['App Usage Time (min/day)'].fillna(df['App Usage Time (min/day)'].mean,inplace = True)

In [82]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              6
App Usage Time (min/day)      0
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        9
User Behavior Class           0
dtype: int64

In [83]:
df.columns

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [84]:
df['Operating System'].fillna(df['Operating System'].median,inplace = True)

In [85]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              0
App Usage Time (min/day)      0
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        9
User Behavior Class           0
dtype: int64

In [86]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace = True)

/var/folders/td/x0tmvm6n1dn552__97jmrspr0000gn/T/ipykernel_15916/2549623796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0],inplace = True)

In [87]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              0
App Usage Time (min/day)      0
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        0
User Behavior Class           0
dtype: int64

In [88]:
df = pd.read_csv('/Users/rashmithav/Desktop/Desktop/datasets_dataminds/user_behavior_missing data-2.csv')
df

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,2,OnePlus 9,Android,268.0,4.7,1331.0,42.0,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154.0,4.0,761.0,32.0,322,42,NaN,2
3,4,Google Pixel 5,Android,239.0,4.8,1676.0,56.0,871,20,NaN,3
4,5,iPhone 12,iOS,187.0,4.3,1367.0,58.0,988,31,Female,3
...,...,...,...,...,...,...,...,...,...,...,...
695,696,iPhone 12,iOS,92.0,3.9,1082.0,26.0,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316.0,6.8,1965.0,68.0,1201,59,Male,4
697,698,Google Pixel 5,Android,99.0,3.1,942.0,22.0,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62.0,1.7,431.0,13.0,224,44,Male,1
699,700,OnePlus 9,Android,212.0,5.4,1306.0,49.0,828,23,Female,3

In [89]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              6
App Usage Time (min/day)      5
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        9
User Behavior Class           0
dtype: int64

In [90]:
df.dropna(subset= ['Age','Gender'],inplace = True)

In [91]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              5
App Usage Time (min/day)      5
Screen On Time (hours/day)    9
Battery Drain (mAh/day)       1
Number of Apps Installed      1
Data Usage (MB/day)           0
Age                           0
Gender                        0
User Behavior Class           0
dtype: int64

In [ ]:
df.dropna(inplace = True)

In [93]:
df['Gender'].value_counts()

Gender
Male      349
Female    321
Name: count, dtype: int64

In [94]:
df.isna().sum()

User ID                       0
Device Model                  0
Operating System              0
App Usage Time (min/day)      0
Screen On Time (hours/day)    0
Battery Drain (mAh/day)       0
Number of Apps Installed      0
Data Usage (MB/day)           0
Age                           0
Gender                        0
User Behavior Class           0
dtype: int64

In [98]:
df.columns

Index(['Device Model', 'Operating System', 'App Usage Time (min/day)',
       'Screen On Time (hours/day)', 'Battery Drain (mAh/day)',
       'Number of Apps Installed', 'Data Usage (MB/day)', 'Age', 'Gender',
       'User Behavior Class'],
      dtype='object')

In [99]:
df.drop(['Operating System'],axis= 1 , inplace = True)

In [100]:
df

,Device Model,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,Google Pixel 5,393.0,6.4,1872.0,67.0,1122,40,Male,4
1,OnePlus 9,268.0,4.7,1331.0,42.0,944,47,Female,3
4,iPhone 12,187.0,4.3,1367.0,58.0,988,31,Female,3
6,Samsung Galaxy S21,350.0,7.3,1802.0,66.0,1054,21,Female,4
7,OnePlus 9,543.0,11.4,2956.0,82.0,1702,31,Male,5
...,...,...,...,...,...,...,...,...,...
695,iPhone 12,92.0,3.9,1082.0,26.0,381,22,Male,2
696,Xiaomi Mi 11,316.0,6.8,1965.0,68.0,1201,59,Male,4
697,Google Pixel 5,99.0,3.1,942.0,22.0,457,50,Female,2
698,Samsung Galaxy S21,62.0,1.7,431.0,13.0,224,44,Male,1
699,OnePlus 9,212.0,5.4,1306.0,49.0,828,23,Female,3

In [102]:
df.drop(columns = ['Age','Gender'],inplace = True)

In [103]:
df

,Device Model,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),User Behavior Class
0,Google Pixel 5,393.0,6.4,1872.0,67.0,1122,4
1,OnePlus 9,268.0,4.7,1331.0,42.0,944,3
4,iPhone 12,187.0,4.3,1367.0,58.0,988,3
6,Samsung Galaxy S21,350.0,7.3,1802.0,66.0,1054,4
7,OnePlus 9,543.0,11.4,2956.0,82.0,1702,5
...,...,...,...,...,...,...,...
695,iPhone 12,92.0,3.9,1082.0,26.0,381,2
696,Xiaomi Mi 11,316.0,6.8,1965.0,68.0,1201,4
697,Google Pixel 5,99.0,3.1,942.0,22.0,457,2
698,Samsung Galaxy S21,62.0,1.7,431.0,13.0,224,1
699,OnePlus 9,212.0,5.4,1306.0,49.0,828,3

In [ ]:
df = pd.read_csv('/Users/rashmithav/Desktop/Desktop/datasets_dataminds/user_behavior_missing data-2.csv')

# Calculate percentage of missing values for each column
missing_percentage = df.isnull().mean() * 100

# Print missing percentages
print(missing_percentage)

User ID                       0.000000
Device Model                  0.000000
Operating System              0.857143
App Usage Time (min/day)      0.714286
Screen On Time (hours/day)    1.285714
Battery Drain (mAh/day)       0.142857
Number of Apps Installed      0.142857
Data Usage (MB/day)           0.000000
Age                           0.000000
Gender                        1.285714
User Behavior Class           0.000000
dtype: float64

In [ ]:
# Total missing values percentage
total_missing_percentage = df.isnull().sum().sum() / (df.size) * 100

print(f"Total Percentage of Missing Values: {total_missing_percentage}%")
# total missing percentageis 2.8 percentage

Total Percentage of Missing Values: 0.40259740259740256%